### ISSUE TITLE
Couldn't complete the installation

### ISSUE THREAD

**Issue by Kavindi183** [fhamborg/news-please#59]
When I try to install this library I got following error.

```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Nishara\\AppData\\Local\\Temp\\pip-install-9axz4aui\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Nishara\AppData\Local\Temp\pip-record-_xo3iyqt\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Nishara\AppData\Local\Temp\pip-install-9axz4aui\Twisted\
```

My python version is python 3.6

**Comment by Yash-Rangarajan** [comment]
Install Visual Studio 2017  Alongwith c== and python development environment integration.
That should fix the issue as News-please requires V C++ build tools.

**Comment by fhamborg** [comment]
thanks @Yash-Rangarajan for your reply! @Kavindi183 , feel free to reopen the issue in case that did not fix the issue.

**Comment by gdprg** [comment]
I am trying to installed news-please on windows. I am also getting the error about Microsoft Visual C++ 14.0....  I installed Visual Studio 2017 along with C++ and python development environment integration.
However, I am still getting the same error.  I am using python version 3.5.4.  Please help.
